### ISSUE TITLE
Stepper crossbar mod?

### ISSUE THREAD

**Issue by drz01** [doudar/SmartSpin2k#74]
![crossbar bits](https://user-images.githubusercontent.com/13085340/105980983-a5308900-60e9-11eb-8feb-e9a7c82072d0.jpg)

Damage sustained during shipping, I suspect. But is it possible to improve tensile strength (by increasing thickness) while remaining compatible? It would make sense if this was an SLA resin print; Digifabster rejects the STL as too thin for FDM.

I shall first attempt a UV plastic repair (Bondic) over the weekend, since the material is translucent.

**Comment by doudar** [comment]
Unfortunately you're the second one with this issue. I suspect it's from the box getting dropped hard on the side and the leverage of the stepper motor breaking the crossbar. It's cold here and that probably doesn't help either. 

I've since redesigned the cover so it has a rim that fits snugly over the top of the stepper for shipping. 

The crossbar strength is adequate for normal operations however so you could try a repair in whatever method you see fit. (Gosh that's a lot of pieces....)

Let me know if you need help getting local reprints or anything else. 

In my next run of those small parts, I'll try nylon which should help for shipping flexibility also.

**Comment by drz01** [comment]
Ok thanks. On closer look it was too shattered, and with pieces missing, for repair. I shall order a rush print with the current spec.

**Comment by doudar** [comment]
Ugh....so sorry about that....
